name: "Terraform Infrastructure Change Management Pipeline with GitHub Actions"

on:
 push:
   branches:
   - spoke-v0.1
 pull_request: {}

env:
 TF_LOG: WARN
 TF_DATA_DIR: "~/.terraform"
 ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
 ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
 AWS_ACCESS_KEY_ID: ${{ secrets.SPOKE_AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.SPOKE_AWS_SECRET_ACCESS_KEY }}
 tf_version: "1.12.2"
 tg_version: "v0.84.1"

jobs:
 terraform:
   name: "Terraform Infrastructure Change Management"
   runs-on: ubuntu-latest
   defaults:
     run:
       shell: bash
       working-directory: .

   steps:
     - name: Add Git credential
       run: |
         git config --global url."https://git:${{ secrets.GIT_PASS }}@github.com/goldstrike77".insteadOf "https://github.com/goldstrike77"
         git config --global url."https://${{ secrets.GIT_PASS }}:x-oauth-basic@github.com/goldstrike77".insteadOf ssh://git@github.com/goldstrike77

     - name: Checkout the repository to the runner
       uses: actions/checkout@v4

     - name: Setup Terraform with specified version on the runner
       uses: hashicorp/setup-terraform@v3
       with:
         terraform_version: ${{ env.tf_version }}

     - name: Terragrunt Install
       uses: userbradley/action-install-terragrunt@v1.1.1
       with:
         version: ${{ env.tg_version }}

     - name: Init
       run: terragrunt init --all -input=false -reconfigure --non-interactive -lock=false

     - name: Plan
       run: terragrunt plan --all --non-interactive -terragrunt-source-update

     - name: Apply
       if: github.event_name == 'push' && github.event.head_commit.message == 'deploy'
       run: terragrunt apply --all --non-interactive

     - name: Destroy
       if: github.event_name == 'push' && github.event.head_commit.message == 'destroy'
       run: terragrunt destroy --all --non-interactive -input=false